from collections.abc import Callable, Iterable, Mapping
from typing import Any, Dict, List
from ._core import DDM

class SmartCache:
    template: Dict[str, Any]
    def __init__(self, template: Mapping[str, Any]) -> None: ...
    def complete(self, raw_data: Mapping[str, Any]) -> Dict[str, Any]: ...
    def complete_batch(self, records: Iterable[Mapping[str, Any]]) -> List[Dict[str, Any]]: ...
    fill: Callable[[Mapping[str, Any]], Dict[str, Any]]
    fill_batch: Callable[[Iterable[Mapping[str, Any]]], List[Dict[str, Any]]]
    def get_missing_keys(self, raw_data: Mapping[str, Any]) -> List[str]: ...
    def get_extra_keys(self, raw_data: Mapping[str, Any]) -> List[str]: ...
    def completion_report(self, raw_data: Mapping[str, Any]) -> Dict[str, Any]: ...
    def update_template(self, new_template: Mapping[str, Any]) -> SmartCache: ...
    def get_stats(self) -> Dict[str, int]: ...
    def reset_stats(self) -> None: ...
SC = SmartCache

class DDMBuilder:
    def __init__(self) -> None: ...
    def set(self, key: str, value: Any) -> DDMBuilder: ...
    def set_many(self, **kwargs: Any) -> DDMBuilder: ...
    def nest(self, key: str, builder_func: Callable[[DDMBuilder], Any]) -> DDMBuilder: ...
    def add_list(self, key: str, values: Iterable[Any]) -> DDMBuilder: ...
    def build(self) -> DDM: ...

def merge_ddms(*ddms: DDM) -> DDM: ...
def compare_ddms(ddm1: DDM, ddm2: DDM) -> Dict[str, Any]: ...
def batch_transform(ddms: Iterable[DDM], transformer: Callable[[DDM], Any]) -> List[Any]: ...
def batch_filter(ddms: Iterable[DDM], predicate: Callable[[DDM], bool]) -> List[DDM]: ...
def validate_ddm_batch(ddms: Iterable[DDM], schema: Dict[str, Any]) -> List[Dict[str, Any]]: ...
def analyze_ddm_structure(ddm: DDM) -> Dict[str, Any]: ...
def get_ddm_size_info(ddm: DDM) -> Dict[str, int]: ...
def create_smart_cache(template: Mapping[str, Any]) -> SmartCache: ...
def fast_complete(template: Mapping[str, Any], raw_data: Mapping[str, Any]) -> Dict[str, Any]: ...
def batch_complete_fast(template: Mapping[str, Any], records: Iterable[Mapping[str, Any]]) -> List[Dict[str, Any]]: ...
