from collections import Counter
from collections.abc import Callable, Hashable, Iterable, Iterator, Mapping, MutableMapping, MutableSequence, Sequence
from typing import Any, Generic, TypeVar, overload
from ._core import DDM

TItem = TypeVar("TItem", bound=Any)
K = TypeVar("K", bound=Hashable)

class BatchPlan:
    def __init__(self) -> None: ...
    def set(self, path: str, value: Any) -> BatchPlan: ...
    def add(self, path: str, amount: float = 1.0) -> BatchPlan: ...
    def subtract(self, path: str, amount: float = 1.0) -> BatchPlan: ...
    sub = subtract
    def multiply(self, path: str, factor: float) -> BatchPlan: ...
    mul = multiply
    def divide(self, path: str, divisor: float) -> BatchPlan: ...
    div = divide
    def clamp(self, path: str, minimum: float, maximum: float) -> BatchPlan: ...
    def clear(self) -> BatchPlan: ...
    def execute(self, collection: DDMCollectionOps[Any]) -> int: ...
    def __len__(self) -> int: ...

class DDMCollectionOps(Generic[TItem]):
    def batch(self) -> BatchPlan: ...
    def path_values(self, path: str, default: Any = None) -> list[Any]: ...
    pluck = path_values
    def set_all(self, path: str, value: Any) -> int: ...
    def apply_path(self, path: str, func: Callable[[Any], Any], *, write_back: bool = True) -> list[Any]: ...
    def map(self, func: Callable[[TItem], Any]) -> list[Any]: ...
    def for_each(self, func: Callable[[TItem], Any]) -> DDMCollectionOps[TItem]: ...
    def reduce(self, func: Callable[[Any, TItem], Any], initial: Any = ...) -> Any: ...
    def filter(self, predicate: Callable[[TItem], bool]) -> list[TItem]: ...
    def filter_path(self, path: str, value: Any = None, *, op: str = "eq") -> list[TItem]: ...
    where = filter_path
    def first(self, predicate: Callable[[TItem], bool] | None = None, default: Any = None) -> TItem | Any: ...
    def first_path(self, path: str, value: Any = None, *, op: str = "eq", default: Any = None) -> TItem | Any: ...
    def any(self, predicate: Callable[[TItem], bool]) -> bool: ...
    def all(self, predicate: Callable[[TItem], bool]) -> bool: ...
    def exists_path(self, path: str, value: Any = None, *, op: str = "eq") -> bool: ...
    def count_path(self, path: str, value: Any = None, *, op: str = "eq") -> int: ...
    def partition_path(self, path: str, value: Any = None, *, op: str = "eq") -> tuple[list[TItem], list[TItem]]: ...
    def update_all(self, **values: Any) -> int: ...
    def update_where(self, predicate: Callable[[TItem], bool], **values: Any) -> int: ...
    def apply_where(self, predicate: Callable[[TItem], bool], path: str, func: Callable[[Any], Any]) -> int: ...
    def increment(self, path: str, amount: float = 1.0) -> int: ...
    def decrement(self, path: str, amount: float = 1.0) -> int: ...
    def multiply(self, path: str, factor: float) -> int: ...
    def divide(self, path: str, divisor: float) -> int: ...
    def clamp(self, path: str, minimum: float, maximum: float) -> int: ...
    def sum(self, path: str) -> float: ...
    def mean(self, path: str) -> float | None: ...
    def min(self, path: str) -> float | None: ...
    def max(self, path: str) -> float | None: ...
    def numeric_count(self, path: str) -> int: ...
    @overload
    def sort_by(self, path: str, *, reverse: bool = False, missing_last: bool = True, inplace: bool = False) -> list[TItem]: ...
    @overload
    def sort_by(self, path: str, *, reverse: bool = False, missing_last: bool = True, inplace: bool = True) -> DDMCollectionOps[TItem]: ...
    def is_sorted(self, path: str, *, reverse: bool = False) -> bool: ...
    def lower_bound(self, path: str, value: Any, *, reverse: bool = False, verify_sorted: bool = True) -> int: ...
    def equal_range(self, path: str, value: Any, *, reverse: bool = False, verify_sorted: bool = True) -> tuple[int, int]: ...
    def binary_search(self, path: str, value: Any, *, reverse: bool = False, verify_sorted: bool = True) -> int: ...
    def nth(self, path: str, n: int, *, largest: bool = False) -> TItem: ...
    def top(self, path: str, n: int = 10, *, largest: bool = True) -> list[TItem]: ...
    def bottom(self, path: str, n: int = 10) -> list[TItem]: ...
    def group_by(self, path: str, default: Any = None) -> dict[Any, list[TItem]]: ...
    def count_by(self, path: str, default: Any = None) -> Counter[Any]: ...
    def distinct(self, path: str, default: Any = None) -> list[Any]: ...
    @overload
    def deduplicate(self, path: str | None = None, *, inplace: bool = False) -> list[TItem]: ...
    @overload
    def deduplicate(self, path: str | None = None, *, inplace: bool = True) -> DDMCollectionOps[TItem]: ...
    def partition(self, predicate: Callable[[TItem], bool]) -> tuple[list[TItem], list[TItem]]: ...
    def chunks(self, size: int) -> Iterator[list[TItem]]: ...
    def take(self, count: int) -> list[TItem]: ...
    def skip(self, count: int) -> list[TItem]: ...
    def sample(self, count: int) -> list[TItem]: ...
    @overload
    def shuffle(self, *, inplace: bool = True) -> DDMCollectionOps[TItem]: ...
    @overload
    def shuffle(self, *, inplace: bool = False) -> list[TItem]: ...
    @overload
    def reverse(self, *, inplace: bool = True) -> DDMCollectionOps[TItem]: ...
    @overload
    def reverse(self, *, inplace: bool = False) -> list[TItem]: ...
    def rename_path(self, old_path: str, new_path: str, *, missing: Any = ...) -> int: ...
    def copy_path(self, source: str, destination: str, *, missing: Any = ...) -> int: ...
    def move_path(self, source: str, destination: str, *, missing: Any = ...) -> int: ...
    def fill_missing(self, path: str, value: Any) -> int: ...
    def delete_path(self, path: str) -> int: ...
    def search(self, *args: Any, **kwargs: Any) -> Any: ...
    def build_search_index(self, *paths: str, **kwargs: Any) -> Any: ...

class ListDDM(DDMCollectionOps[DDM], MutableSequence[DDM]):
    def __init__(self, values: Iterable[DDM | Mapping[str, Any]] = ()) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> DDM: ...
    @overload
    def __getitem__(self, index: slice) -> list[DDM]: ...
    def __setitem__(self, index: int | slice, value: DDM | Mapping[str, Any] | Iterable[DDM | Mapping[str, Any]]) -> None: ...
    def __delitem__(self, index: int | slice) -> None: ...
    def insert(self, index: int, value: DDM | Mapping[str, Any]) -> None: ...
    def __iter__(self) -> Iterator[DDM]: ...
    def indexed(self, *paths: str, **kwargs: Any) -> Any: ...
    def __repr__(self) -> str: ...

class SetDDM(DDMCollectionOps[DDM]):
    def __init__(self, values: Iterable[DDM | Mapping[str, Any]] = (), *, key: Callable[[DDM], Hashable] | None = None, key_path: str | None = None) -> None: ...
    def add(self, value: DDM | Mapping[str, Any]) -> bool: ...
    def discard(self, value: DDM | Mapping[str, Any]) -> bool: ...
    def remove(self, value: DDM | Mapping[str, Any]) -> None: ...
    def __contains__(self, value: object) -> bool: ...
    def __iter__(self) -> Iterator[DDM]: ...
    def __len__(self) -> int: ...
    def rehash(self) -> SetDDM: ...
    def __repr__(self) -> str: ...

class DictDDM(DDMCollectionOps[DDM], MutableMapping[K, DDM], Generic[K]):
    def __init__(self, values: Mapping[K, DDM | Mapping[str, Any]] | None = None, **kwargs: Any) -> None: ...
    def __getitem__(self, key: K) -> DDM: ...
    def __setitem__(self, key: K, value: DDM | Mapping[str, Any]) -> None: ...
    def __delitem__(self, key: K) -> None: ...
    def __iter__(self) -> Iterator[K]: ...
    def __len__(self) -> int: ...
    def values(self) -> Any: ...
    def items(self) -> Any: ...
    def keys_for(self, path: str, value: Any = None, *, op: str = "eq") -> list[K]: ...
    def indexed(self, *paths: str, **kwargs: Any) -> Any: ...
    def __repr__(self) -> str: ...

class DDMTable(ListDDM):
    def columns(self) -> list[str]: ...
    def select(self, *paths: str) -> list[dict[str, Any]]: ...
    def assign(self, **path_values: Any) -> DDMTable: ...
    def query(self, **criteria: Any) -> DDMTable: ...
