from collections.abc import ItemsView, Iterable, Iterator, KeysView, Mapping, ValuesView
from typing import Any, Callable, Dict, Type, TypeVar, Union, overload

T_DDM = TypeVar("T_DDM", bound="DDM")

class DDM:
    _data: Dict[str, Any]
    _schema: Dict[str, Any] | None
    def __init__(self, data: Mapping[str, Any]) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self, indent: int = 2, include_private: bool = False) -> str: ...
    @staticmethod
    def from_json(json_str: str) -> DDM: ...
    @overload
    def get_path(self, path: str) -> Any | None: ...
    @overload
    def get_path(self, path: str, default: T_DDM) -> Any | T_DDM: ...
    def get_path(self, path: str, default: Any = None) -> Any: ...
    def set_path(self, path: str, value: Any) -> bool: ...
    def has_path(self, path: str) -> bool: ...
    def clone(self: T_DDM) -> T_DDM: ...
    def copy(self: T_DDM) -> T_DDM: ...
    def to_flat_dict(self, prefix: str = "", separator: str = ".") -> Dict[str, Any]: ...
    def merge(self: T_DDM, other: DDM | Mapping[str, Any]) -> T_DDM: ...
    def update(self: T_DDM, *args: Mapping[str, Any], **kwargs: Any) -> T_DDM: ...
    def diff(self, other: DDM) -> Dict[str, Any]: ...
    def validate_schema(self, schema: Dict[str, Any]) -> Dict[str, Any]: ...
    def keys(self) -> KeysView[str]: ...
    def values(self) -> ValuesView[Any]: ...
    def items(self) -> ItemsView[str, Any]: ...
    @overload
    def get(self, key: str) -> Any | None: ...
    @overload
    def get(self, key: str, default: T_DDM) -> Any | T_DDM: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def setdefault(self, key: str, default: Any = None) -> Any: ...
    @overload
    def pop(self, key: str) -> Any: ...
    @overload
    def pop(self, key: str, default: T_DDM) -> Any | T_DDM: ...
    def pop(self, key: str, default: Any = ...) -> Any: ...
    def popitem(self) -> tuple[str, Any]: ...
    def clear(self) -> None: ...
    def filter_keys(self, keys: Iterable[str]) -> DDM: ...
    def exclude_keys(self, keys: Iterable[str]) -> DDM: ...
    def pick(self, *keys: str) -> DDM: ...
    def omit(self, *keys: str) -> DDM: ...
    def search(self, query: Any, case_sensitive: bool = False) -> Dict[str, Any]: ...
    def find_by_type(self, value_type: Type[Any]) -> Dict[str, Any]: ...
    def transform(self, func: Callable[[Any], Any]) -> DDM: ...
    def map_attributes(self, mapping: Mapping[str, str | Callable[[Any], Any]]) -> DDM: ...
    def sort_by_key(self, reverse: bool = False) -> DDM: ...
    def sort_by_value(self, reverse: bool = False) -> DDM: ...
    def group_by(self, func: Callable[[str, Any], Any]) -> Dict[Any, Dict[str, Any]]: ...
    def aggregate(self, funcs: Callable[[Iterable[Any]], Any] | Mapping[str, Callable[[Iterable[Any]], Any]]) -> Any: ...
    def get_types(self) -> Dict[str, Type[Any]]: ...
    def has_type(self, key: str, value_type: Type[Any]) -> bool: ...
    def count(self) -> int: ...
    def is_empty(self) -> bool: ...
    def memory_info(self, recursive: bool = True) -> Dict[str, int]: ...
    def compact(self: T_DDM, intern_keys: bool = True) -> T_DDM: ...
    def to_csv(self) -> str: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
