from collections.abc import Callable, Iterable, Iterator, Mapping, Sequence
from typing import Any, Dict, List
from ._core import DDM

class Range(DDM):
    min_val: float
    max_val: float
    step: float
    def __init__(self, min_val: float = 0.0, max_val: float = 1.0, step: float = 1.0) -> None: ...
    def contains(self, value: float) -> bool: ...
    def clamp(self, value: float) -> float: ...
    def span(self) -> float: ...
    def midpoint(self) -> float: ...
    def normalize(self, value: float) -> float: ...
    def denormalize(self, value: float) -> float: ...
    def random(self) -> float: ...
    def iterate(self) -> Iterator[float]: ...
    def subdivide(self, parts: int) -> List[Range]: ...
    def intersect(self, other: Range) -> Range | None: ...
    def overlaps(self, other: Range) -> bool: ...

class Vector(DDM):
    components: List[float]
    def __init__(self, components: Sequence[float]) -> None: ...
    def magnitude(self) -> float: ...
    def normalize(self) -> Vector: ...
    def dot(self, other: Vector) -> float: ...
    def cross(self, other: Vector) -> Vector: ...
    def distance_to(self, other: Vector) -> float: ...
    def angle_to(self, other: Vector) -> float: ...
    def add(self, other: Vector) -> Vector: ...
    def subtract(self, other: Vector) -> Vector: ...
    def scale(self, scalar: float) -> Vector: ...
    def project_onto(self, other: Vector) -> Vector: ...
    def perpendicular(self) -> Vector: ...
    def lerp(self, other: Vector, t: float) -> Vector: ...

class Timeline(DDM):
    start_time: float
    end_time: float
    events: List[Dict[str, Any]]
    def __init__(self, start_time: float = 0.0, end_time: float = 1.0, events: List[Dict[str, Any]] | None = None) -> None: ...
    def add_event(self, time: float, name: str, data: Any = None) -> Dict[str, Any]: ...
    def remove_event(self, name: str) -> bool: ...
    def get_event(self, name: str) -> Dict[str, Any] | None: ...
    def events_at(self, time: float) -> List[Dict[str, Any]]: ...
    def events_between(self, start: float, end: float) -> List[Dict[str, Any]]: ...
    def duration(self) -> float: ...
    def get_progress(self, time: float) -> float: ...
    def sort(self, reverse: bool = False) -> Timeline: ...
    def reverse(self) -> Timeline: ...

class Dataset(DDM):
    columns: List[str]
    rows: List[Dict[str, Any]]
    def __init__(self, columns: Sequence[str] | None = None, rows: Sequence[Mapping[str, Any]] | None = None) -> None: ...
    def add_row(self, row: Mapping[str, Any]) -> Dataset: ...
    def add_column(self, name: str, default: Any = None) -> Dataset: ...
    def remove_column(self, name: str) -> Dataset: ...
    def filter_rows(self, predicate: Callable[[Dict[str, Any]], bool]) -> Dataset: ...
    def map_column(self, name: str, func: Callable[[Any], Any]) -> Dataset: ...
    def sort_by(self, column: str, reverse: bool = False) -> Dataset: ...
    def group_by(self, column: str) -> Dict[Any, Dataset]: ...
    def aggregate(self, column: str, func: Callable[[Iterable[Any]], Any]) -> Any: ...
    def stats(self, column: str) -> Dict[str, float]: ...
    def to_csv(self) -> str: ...
    def transpose(self) -> List[List[Any]]: ...

class Size(DDM):
    width: float
    height: float
    def __init__(self, width: float = 0.0, height: float = 0.0) -> None: ...
    def area(self) -> float: ...
    def perimeter(self) -> float: ...
    def aspect_ratio(self) -> float: ...
    def scale(self, factor: float) -> Size: ...
    def fit_inside(self, other: Size, *, upscale: bool = False) -> Size: ...
    def contains(self, other: Size) -> bool: ...

class Point(DDM):
    x: float
    y: float
    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...
    def distance_to(self, other: Point) -> float: ...
    def midpoint(self, other: Point) -> Point: ...
    def translate(self, dx: float = 0.0, dy: float = 0.0) -> Point: ...
    def scale(self, factor: float, origin: Point | None = None) -> Point: ...
    def to_vector(self) -> Vector: ...

class Color(DDM):
    r: int
    g: int
    b: int
    a: int
    def __init__(self, r: int = 0, g: int = 0, b: int = 0, a: int = 255) -> None: ...
    @classmethod
    def from_hex(cls, value: str) -> Color: ...
    def to_hex(self, include_alpha: bool = False) -> str: ...
    def normalized(self) -> tuple[float, float, float, float]: ...
    def blend(self, other: Color, t: float = 0.5) -> Color: ...
    def luminance(self) -> float: ...
    def contrast_ratio(self, other: Color) -> float: ...

class Matrix(DDM):
    rows: List[List[float]]
    @property
    def shape(self) -> tuple[int, int]: ...
    def __init__(self, rows: Sequence[Sequence[float]]) -> None: ...
    @classmethod
    def identity(cls, size: int) -> Matrix: ...
    def transpose(self) -> Matrix: ...
    def add(self, other: Matrix) -> Matrix: ...
    def subtract(self, other: Matrix) -> Matrix: ...
    def scale(self, scalar: float) -> Matrix: ...
    def matmul(self, other: Matrix) -> Matrix: ...
    def vector_mul(self, vector: Vector) -> Vector: ...

class TreeDDM(DDM):
    value: Any
    children: List[TreeDDM]
    def __init__(self, value: Any = None, children: Iterable[TreeDDM] | None = None, **data: Any) -> None: ...
    def add_child(self, child: Any, **data: Any) -> TreeDDM: ...
    def walk(self, order: str = "dfs") -> Iterator[TreeDDM]: ...
    def find(self, predicate: Callable[[TreeDDM], bool]) -> TreeDDM | None: ...
    def depth(self) -> int: ...
    def size(self) -> int: ...
