from collections.abc import Iterator, Mapping
from typing import Any, Callable, Dict, TypeVar, overload
from ._core import DDM

T = TypeVar("T")

class FrozenDDM(DDM):
    def __init__(self, data: Mapping[str, Any]) -> None: ...
    def __hash__(self) -> int: ...
    def thaw(self) -> DDM: ...

class IdentityDDM(DDM):
    def __hash__(self) -> int: ...

class PackedDDM(Mapping[str, Any]):
    def __init__(self, data: Mapping[str, Any], *, intern_keys: bool = True) -> None: ...
    @property
    def _native_data(self) -> Dict[str, Any]: ...
    @property
    def _data(self) -> Dict[str, Any]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def to_json(self, indent: int = 2) -> str: ...
    @overload
    def get_path(self, path: str) -> Any | None: ...
    @overload
    def get_path(self, path: str, default: T) -> Any | T: ...
    def get_path(self, path: str, default: Any = None) -> Any: ...
    def set_path(self, path: str, value: Any) -> bool: ...
    def has_path(self, path: str) -> bool: ...
    def clone(self) -> PackedDDM: ...
    def copy(self) -> PackedDDM: ...
    def to_flat_dict(self, prefix: str = "", separator: str = ".") -> Dict[str, Any]: ...
    def memory_info(self, recursive: bool = True) -> Dict[str, int]: ...
    def freeze(self) -> FrozenDDM: ...
    def __repr__(self) -> str: ...

class SchemaDDM(DDM):
    def __init__(self, data: Mapping[str, Any], schema: Mapping[str, Any], *, strict: bool = True) -> None: ...
    def validate(self) -> Dict[str, Any]: ...
    def set_validated(self, path: str, value: Any) -> SchemaDDM: ...

class DefaultDDM(DDM):
    def __init__(self, data: Mapping[str, Any], default_factory: Callable[[], Any] = ...) -> None: ...
    def __getitem__(self, key: str) -> Any: ...

class LazyDDM(DDM):
    def __init__(self, data: Mapping[str, Any], lazy: Mapping[str, Callable[[LazyDDM], Any]] | None = None) -> None: ...
    def invalidate(self, *fields: str) -> LazyDDM: ...

class ViewDDM(Mapping[str, Any]):
    def __init__(self, mapping: Dict[str, Any]) -> None: ...
    @property
    def _native_data(self) -> Dict[str, Any]: ...
    @property
    def _data(self) -> Dict[str, Any]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def to_dict(self) -> Dict[str, Any]: ...
    @overload
    def get_path(self, path: str) -> Any | None: ...
    @overload
    def get_path(self, path: str, default: T) -> Any | T: ...
    def get_path(self, path: str, default: Any = None) -> Any: ...
    def set_path(self, path: str, value: Any) -> bool: ...
    def has_path(self, path: str) -> bool: ...
    def __repr__(self) -> str: ...
