from typing import ClassVar
class Colors:
    RESET: ClassVar[str]; BRIGHT: ClassVar[str]; DIM: ClassVar[str]; ITALIC: ClassVar[str]; UNDERLINE: ClassVar[str]; BLINK: ClassVar[str]; REVERSE: ClassVar[str]; HIDDEN: ClassVar[str]; STRIKETHROUGH: ClassVar[str]
    BLACK: ClassVar[str]; RED: ClassVar[str]; GREEN: ClassVar[str]; YELLOW: ClassVar[str]; BLUE: ClassVar[str]; MAGENTA: ClassVar[str]; CYAN: ClassVar[str]; WHITE: ClassVar[str]
    BRIGHT_BLACK: ClassVar[str]; BRIGHT_RED: ClassVar[str]; BRIGHT_GREEN: ClassVar[str]; BRIGHT_YELLOW: ClassVar[str]; BRIGHT_BLUE: ClassVar[str]; BRIGHT_MAGENTA: ClassVar[str]; BRIGHT_CYAN: ClassVar[str]; BRIGHT_WHITE: ClassVar[str]
    BG_BLACK: ClassVar[str]; BG_RED: ClassVar[str]; BG_GREEN: ClassVar[str]; BG_YELLOW: ClassVar[str]; BG_BLUE: ClassVar[str]; BG_MAGENTA: ClassVar[str]; BG_CYAN: ClassVar[str]; BG_WHITE: ClassVar[str]
    BG_BRIGHT_BLACK: ClassVar[str]; BG_BRIGHT_RED: ClassVar[str]; BG_BRIGHT_GREEN: ClassVar[str]; BG_BRIGHT_YELLOW: ClassVar[str]; BG_BRIGHT_BLUE: ClassVar[str]; BG_BRIGHT_MAGENTA: ClassVar[str]; BG_BRIGHT_CYAN: ClassVar[str]; BG_BRIGHT_WHITE: ClassVar[str]
    @classmethod
    def rgb(cls, r: int, g: int, b: int) -> str: ...
    @classmethod
    def bg_rgb(cls, r: int, g: int, b: int) -> str: ...
    @staticmethod
    def ansi256(index: int) -> str: ...
    @staticmethod
    def bg_ansi256(index: int) -> str: ...
    @staticmethod
    def strip(text: object) -> str: ...
    @classmethod
    def wrap(cls, text: object, *styles: str, reset: bool = True) -> str: ...
    @classmethod
    def foreground(cls, rgb: tuple[int, int, int], text: object) -> str: ...
    @classmethod
    def background(cls, rgb: tuple[int, int, int], text: object) -> str: ...
    @classmethod
    def gradient(cls, text: str, start: tuple[int, int, int], end: tuple[int, int, int]) -> str: ...
