from collections.abc import Hashable, Iterable, Iterator, Mapping, Sequence
from enum import Enum
from pathlib import Path
from typing import Any, Callable, Final

class SearchAlgorithm(str, Enum):
    AUTO: SearchAlgorithm
    HYBRID: SearchAlgorithm
    EXACT: SearchAlgorithm
    PREFIX: SearchAlgorithm
    SUBSTRING: SearchAlgorithm
    REGEX: SearchAlgorithm
    LEVENSHTEIN: SearchAlgorithm
    DAMERAU: SearchAlgorithm
    JARO_WINKLER: SearchAlgorithm
    TRIGRAM: SearchAlgorithm
    BM25: SearchAlgorithm

class SearchDocument:
    id: Hashable
    text: str
    metadata: dict[str, Any]
    tags: tuple[str, ...]
    fields: dict[str, Any]
    def __init__(self, id: Hashable, text: str, metadata: dict[str, Any] = ..., tags: tuple[str, ...] = (), fields: dict[str, Any] = ...) -> None: ...
    def searchable_text(self) -> str: ...

class SearchResult:
    sort_index: float
    score: float
    document: SearchDocument
    algorithm: str
    positions: tuple[int, ...]
    matched_terms: tuple[str, ...]
    details: dict[str, float]
    def __init__(self, score: float, document: SearchDocument, algorithm: str = "hybrid", positions: tuple[int, ...] = (), matched_terms: tuple[str, ...] = (), details: dict[str, float] = ...) -> None: ...
    @property
    def value(self) -> Any: ...

class SearchStats:
    documents: int
    tokens: int
    unique_tokens: int
    average_document_length: float
    def __init__(self, documents: int, tokens: int, unique_tokens: int, average_document_length: float) -> None: ...

class SearchQuery:
    text: str
    algorithm: SearchAlgorithm | str
    limit: int | None
    min_score: float
    filters: Mapping[str, Any] | None
    regex_flags: int
    def __init__(self, text: str, algorithm: SearchAlgorithm | str = SearchAlgorithm.HYBRID, limit: int | None = 10, min_score: float = 0.0, filters: Mapping[str, Any] | None = None, regex_flags: int = 0) -> None: ...

class Posting:
    doc_id: Hashable
    term_frequency: int
    def __init__(self, doc_id: Hashable, term_frequency: int) -> None: ...

class AutocompleteEntry:
    term: str
    payload: Any
    weight: float
    def __init__(self, term: str, payload: Any = None, weight: float = 1.0) -> None: ...

class PatternMatch:
    pattern: str
    start: int
    end: int
    pattern_index: int
    def __init__(self, pattern: str, start: int, end: int, pattern_index: int) -> None: ...

class FuzzyMatcher:
    @staticmethod
    def levenshtein(a: str, b: str, *, case_sensitive: bool = False) -> int: ...
    @staticmethod
    def damerau_levenshtein(a: str, b: str, *, case_sensitive: bool = False) -> int: ...
    @staticmethod
    def levenshtein_ratio(a: str, b: str, *, damerau: bool = False, case_sensitive: bool = False) -> float: ...
    @staticmethod
    def jaro_winkler(a: str, b: str, *, case_sensitive: bool = False) -> float: ...
    @staticmethod
    def trigram(a: str, b: str, *, case_sensitive: bool = False) -> float: ...
    @staticmethod
    def hybrid(a: str, b: str, *, case_sensitive: bool = False) -> float: ...

class InvertedIndex:
    def __init__(self) -> None: ...
    def add(self, doc_id: Hashable, tokens: Iterable[str]) -> None: ...
    def remove(self, doc_id: Hashable) -> bool: ...
    def clear(self) -> None: ...
    def tokens(self, doc_id: Hashable) -> tuple[str, ...]: ...
    def postings(self, term: str) -> tuple[Posting, ...]: ...
    def terms(self) -> Iterator[str]: ...
    def prefix_terms(self, prefix: str, *, limit: int | None = None) -> list[str]: ...
    def fuzzy_terms(self, query: str, *, algorithm: SearchAlgorithm | str = SearchAlgorithm.HYBRID, threshold: float = 0.6, limit: int = 8) -> list[tuple[str, float]]: ...
    def candidate_ids(self, terms: Iterable[str]) -> set[Hashable]: ...
    def bm25(self, query_tokens: Iterable[str], *, candidates: set[Hashable] | None = None, k1: float = 1.5, b: float = 0.75) -> dict[Hashable, float]: ...
    def document_count(self) -> int: ...
    def token_count(self) -> int: ...
    def unique_token_count(self) -> int: ...

class SearchIndex:
    def __init__(self, documents: Iterable[SearchDocument | Mapping[str, Any] | str] | None = None, *, case_sensitive: bool = False) -> None: ...
    def add(self, document: SearchDocument | Mapping[str, Any] | str, *, doc_id: Hashable | None = None) -> SearchDocument: ...
    def extend(self, documents: Iterable[SearchDocument | Mapping[str, Any] | str]) -> SearchIndex: ...
    def remove(self, doc_id: Hashable) -> bool: ...
    def update(self, doc_id: Hashable, **changes: Any) -> SearchDocument: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[SearchDocument]: ...
    def stats(self) -> SearchStats: ...
    def inverted_index(self) -> InvertedIndex: ...
    def search(self, query: str | SearchQuery, *, algorithm: SearchAlgorithm | str = SearchAlgorithm.HYBRID, limit: int | None = 10, min_score: float = 0.0, filters: Mapping[str, Any] | None = None, regex_flags: int = 0) -> list[SearchResult]: ...

class BM25Index(SearchIndex):
    def search(self, query: str | SearchQuery, **kwargs: Any) -> list[SearchResult]: ...

class AutocompleteIndex:
    def __init__(self, entries: Iterable[str | AutocompleteEntry | tuple[str, Any] | tuple[str, Any, float]] = (), *, case_sensitive: bool = False) -> None: ...
    def add(self, entry: str | AutocompleteEntry | tuple[str, Any] | tuple[str, Any, float], payload: Any = None, weight: float = 1.0) -> AutocompleteEntry: ...
    def suggest(self, prefix: str, *, limit: int = 10, fuzzy_fallback: bool = True, min_score: float = 0.62) -> list[AutocompleteEntry]: ...
    def __len__(self) -> int: ...

class MultiPatternSearch:
    def __init__(self, patterns: Iterable[str], *, case_sensitive: bool = False) -> None: ...
    def find(self, text: str) -> list[PatternMatch]: ...
    def contains_any(self, text: str) -> bool: ...

class NumericSearch:
    def __init__(self, values: Iterable[tuple[float, Any]] = ()) -> None: ...
    def add(self, value: float, payload: Any = None) -> None: ...
    def range(self, minimum: float, maximum: float) -> list[tuple[float, Any]]: ...
    def nearest(self, value: float, k: int = 1) -> list[tuple[float, Any]]: ...
    def __len__(self) -> int: ...

class StructuredSearch:
    def __init__(self, records: Iterable[Mapping[str, Any]] = (), *, id_field: str = "id", field_weights: Mapping[str, float] | None = None, case_sensitive: bool = False) -> None: ...
    def add(self, record: Mapping[str, Any]) -> SearchDocument: ...
    def search(self, query: str | SearchQuery, **kwargs: Any) -> list[SearchResult]: ...

class FileSearchEngine:
    def __init__(self, root: str | Path = ".", *, content: bool = False, max_content_bytes: int = 2_000_000, extensions: Iterable[str] | None = None, case_sensitive: bool = False) -> None: ...
    def refresh(self) -> FileSearchEngine: ...
    def search_results(self, query: str | SearchQuery, *, extension: str | Sequence[str] | None = None, min_size: int | None = None, max_size: int | None = None, **kwargs: Any) -> list[SearchResult]: ...
    def search(self, query: str | SearchQuery, **kwargs: Any) -> list[str]: ...

class GenerateTags:
    def __init__(self, terms: str | list[str], lowercase: bool = True, clean_special_chars: bool = True, min_words: int = 1, max_words: int | None = None, replacements: dict[str, str] | None = None, stop_words: list[str] | None = None, max_tags: int = 10_000) -> None: ...
    def get_tags(self) -> list[str]: ...

class SearchData:
    def __init__(self, data: list[dict[str, Any]]) -> None: ...
    def get_tags(self) -> list[str]: ...
    def get(self, tag: str) -> list[Any]: ...
    def __getitem__(self, tag: str) -> list[Any]: ...
    def __contains__(self, tag: object) -> bool: ...
    def __repr__(self) -> str: ...

class Search:
    def __init__(self, sdata: SearchData, only_tag: bool = False) -> None: ...
    def search(self, query: str) -> list[Any]: ...
    def ranked(self, query: str, **kwargs: Any) -> list[SearchResult]: ...

class SearchFile:
    def __init__(self, root: str | Path = ".") -> None: ...
    def search(self, query: str, content: bool = False, case_sensitive: bool = False) -> list[str]: ...

class DDMSearchHit:
    item: Any
    key: Any
    path: str
    value: Any
    score: float
    algorithm: str
    def __init__(self, item: Any, key: Any, path: str, value: Any, score: float = 1.0, algorithm: str = "exact") -> None: ...

class DDMPathIndex:
    path: str
    case_sensitive: bool
    def __init__(self, path: str, entries: Sequence[tuple[Any, Any]], *, text: bool = True, case_sensitive: bool = False, objects: Mapping[Any, Any] | None = None) -> None: ...
    def exact(self, value: Any) -> list[DDMSearchHit]: ...
    def range(self, minimum: Any = None, maximum: Any = None, *, include_min: bool = True, include_max: bool = True) -> list[DDMSearchHit]: ...
    def prefix(self, prefix: str, *, limit: int | None = None) -> list[DDMSearchHit]: ...
    def text(self, query: str, *, algorithm: SearchAlgorithm | str = SearchAlgorithm.HYBRID, limit: int | None = 10, min_score: float = 0.0) -> list[DDMSearchHit]: ...
    def contains(self, needle: Any, *, case_sensitive: bool | None = None) -> list[DDMSearchHit]: ...
    def stats(self) -> dict[str, int]: ...

class DDMCompositeIndex:
    def __init__(self, paths: Sequence[str], entries: Sequence[tuple[Any, Any]], *, objects: Mapping[Any, Any] | None = None) -> None: ...
    def find(self, *values: Any) -> list[Any]: ...

class DDMSearchEngine:
    def __init__(self, source: Any, *, case_sensitive: bool = False) -> None: ...
    def refresh(self) -> DDMSearchEngine: ...
    def invalidate(self, paths: Iterable[str] | None = None) -> None: ...
    def create_index(self, path: str, *, text: bool = True) -> DDMPathIndex: ...
    def create_indexes(self, *paths: str, text: bool = True) -> DDMSearchEngine: ...
    def create_composite_index(self, *paths: str) -> DDMCompositeIndex: ...
    def find(self, path: str, value: Any = None, *, op: str = "eq", limit: int | None = None, use_index: bool = True) -> list[Any]: ...
    def find_one(self, path: str, value: Any = None, *, op: str = "eq", default: Any = None, use_index: bool = True) -> Any: ...
    def exists(self, path: str, value: Any = None, *, op: str = "eq") -> bool: ...
    def count(self, path: str, value: Any = None, *, op: str = "eq") -> int: ...
    def between(self, path: str, minimum: Any, maximum: Any, *, include_min: bool = True, include_max: bool = True) -> list[Any]: ...
    def text(self, path: str, query: str, *, algorithm: SearchAlgorithm | str = SearchAlgorithm.HYBRID, limit: int | None = 10, min_score: float = 0.0, hits: bool = False) -> Any: ...
    def composite(self, paths: Sequence[str], values: Sequence[Any]) -> list[Any]: ...
    def where(self, **lookups: Any) -> list[Any]: ...
    def order_by(self, path: str, *, reverse: bool = False, missing_last: bool = True) -> list[Any]: ...
    def values(self, path: str, default: Any = None) -> list[Any]: ...
    def stats(self) -> dict[str, Any]: ...

class ApplicationSearch:
    def __init__(self, *, case_sensitive: bool = False) -> None: ...
    def add(self, doc_id: Hashable, title: str, body: str = "", *, tags: Iterable[str] = (), fields: Mapping[str, Any] | None = None, payload: Any = None, autocomplete_weight: float = 1.0) -> SearchDocument: ...
    def update(self, doc_id: Hashable, *, title: str | None = None, body: str | None = None, tags: Iterable[str] | None = None, fields: Mapping[str, Any] | None = None, payload: Any = ..., autocomplete_weight: float | None = None) -> SearchDocument: ...
    def remove(self, doc_id: Hashable) -> bool: ...
    def search_results(self, query: str | SearchQuery, **kwargs: Any) -> list[SearchResult]: ...
    def search(self, query: str | SearchQuery, **kwargs: Any) -> list[Any]: ...
    def suggest(self, prefix: str, *, limit: int = 10, fuzzy: bool = True) -> list[AutocompleteEntry]: ...
    def facet(self, field: str, *, query: str | None = None, limit: int | None = None) -> list[tuple[Any, int]]: ...
    def stats(self) -> SearchStats: ...

SearchEngine = ApplicationSearch
DDMIndex = DDMPathIndex

def tokenize(text: Any, *, case_sensitive: bool = False, min_length: int = 1) -> list[str]: ...
