from collections.abc import Iterator, Mapping
from typing import Any

class Debugger:
    COLORS: dict[str, str]
    SYMBOLS: dict[str, str]
    level: int
    DefaultSymbol: bool
    ansi: bool
    def __init__(self, level: int = 0, DefaultSymbol: bool = False) -> None: ...
    def info(self, message: str) -> None: ...
    def debug(self, message: str) -> None: ...
    def success(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
    def critical(self, message: str) -> None: ...
    def custom(self, message: str, color_code: str = "\x1b[1;95m", symbol: str = "*") -> None: ...
    def set_level(self, level: int) -> None: ...

class FileBase:
    SUPPORTED_FORMATS: list[str]
    filefolder: str | None
    debug: bool
    debugger: Debugger
    def __init__(self, filefolder: str | None = None, debug: bool = False, debugger: Debugger | None = None) -> None: ...
    def get_info(self, path: str) -> dict[str, Any]: ...
    def rename_file(self, old_path: str, new_name: str) -> bool: ...
    def rename_folder(self, old_path: str, new_name: str) -> bool: ...
    def create_shortcut(self, target_path: str, shortcut_path: str, description: str = "") -> bool: ...
    def list_files_and_folders(self, path: str | None = None) -> list[str]: ...
    def create_folder(self, folder_path: str) -> bool: ...
    def copy_file(self, source: str, destination: str) -> bool: ...
    def copy_folder(self, source: str, destination: str) -> bool: ...
    def move_file(self, source: str, destination: str) -> bool: ...
    def move_folder(self, source: str, destination: str) -> bool: ...
    def delete_file(self, path: str) -> bool: ...
    def delete_folder(self, path: str) -> bool: ...
    def json_read(self, path: str, default: dict[str, Any] | list[Any] | None = None) -> dict[str, Any] | list[Any]: ...
    def json_write(self, path: str, data: dict[str, Any] | list[Any]) -> None: ...
    def txt_read_str(self, path: str) -> str: ...
    def txt_read_linear(self, path: str) -> dict[str, str]: ...
    def txt_write_str(self, path: str, content: str) -> None: ...
    def txt_write_linear(self, path: str, data: Mapping[int, str]) -> None: ...
    def exists(self, path: str) -> bool: ...
    def is_file(self, path: str) -> bool: ...
    def is_folder(self, path: str) -> bool: ...
    def file_size(self, path: str) -> int: ...
    def directory_size(self, path: str | None = None, recursive: bool = True) -> int: ...
    def read_bytes(self, path: str) -> bytes: ...
    def write_bytes(self, path: str, data: bytes | bytearray | memoryview, append: bool = False) -> None: ...
    def append_bytes(self, path: str, data: bytes | bytearray | memoryview) -> None: ...
    def touch(self, path: str) -> bool: ...
    def line_count(self, path: str) -> int: ...
    def compare_files(self, first: str, second: str) -> bool: ...
    def checksum(self, path: str, algorithm: str = "sha256") -> str: ...
    def head(self, path: str, lines: int = 10) -> list[str]: ...
    def tail(self, path: str, lines: int = 10, block_size: int = 8192) -> list[str]: ...
    def atomic_write_text(self, path: str, content: str) -> None: ...
    def atomic_write_bytes(self, path: str, data: bytes | bytearray | memoryview) -> None: ...
    def atomic_write_json(self, path: str, data: dict[str, Any] | list[Any], indent: int = 4) -> None: ...
    def find_files(self, pattern: str = "*", path: str | None = None, *, recursive: bool = True, extensions: list[str] | None = None, min_size: int | None = None, max_size: int | None = None) -> list[str]: ...
    def read_chunks(self, path: str, chunk_size: int = 1024 * 1024) -> Iterator[bytes]: ...
    def backup(self, path: str, destination: str | None = None) -> str: ...
    def log_read(self, path: str) -> dict[str, str]: ...
    def log_write(self, path: str, content: str) -> None: ...
    def log_write_entry(self, path: str, entry: str) -> None: ...
