from collections.abc import Sequence
from typing import Any
class FileExtraMixin:
    def md_write(self, path: str, content: str, append: bool = False) -> None: ...
    def rtf_write(self, path: str, content: str, append: bool = False) -> None: ...
    def html_write(self, path: str, content: str, append: bool = False) -> None: ...
    def css_write(self, path: str, content: str, append: bool = False) -> None: ...
    def js_write(self, path: str, content: str, append: bool = False) -> None: ...
    def tex_write(self, path: str, content: str) -> None: ...
    def tex_append(self, path: str, content: str) -> None: ...
    def py_write(self, path: str, content: str, append: bool = False) -> None: ...
    def handle_compressed(self, path: str, action: str, target: str | None = None) -> Any: ...
    def sql_execute(self, path: str, query: str, params: Sequence[Any] = ()) -> Any: ...
    @staticmethod
    def markdown_to_latex(markdown: str) -> str: ...
    @staticmethod
    def latex_compile(content: str) -> str: ...
    @staticmethod
    def tex_to_markdown(content: str) -> str: ...
    def latex_to_html(self, content: str, output_path: str | None = None) -> str: ...
    def latex_to_image(self, content: str, output_path: str) -> str: ...
    def py_run(self, path: str, args: Sequence[str] | None = None, terminal: bool = False) -> str | None: ...
    def py_add_code(self, path: str, code: str, position: str | int = "end") -> None: ...
    def js_run(self, path: str, args: Sequence[str] | None = None, terminal: bool = False) -> str | None: ...
