from typing import Any
class FileFormatsMixin:
    def pdf_read(self, path: str) -> str: ...
    def pdf_write(self, path: str, content: str) -> None: ...
    def xml_read(self, path: str) -> dict[str, Any] | None: ...
    def xml_write(self, path: str, data: dict[str, Any], root_element: str = "root") -> None: ...
    def xml_append(self, path: str, data: dict[str, Any], root_element: str = "root") -> None: ...
    def xml_find(self, path: str, query: str) -> dict[str, Any] | None: ...
    def csv_read(self, path: str, delimiter: str = ",", quotechar: str = '"') -> list[dict[str, str]]: ...
    def csv_write(self, path: str, data: list[dict[str, str]], fieldnames: list[str] | None = None, delimiter: str = ",", quotechar: str = '"') -> None: ...
    def csv_append(self, path: str, data: list[dict[str, str]], fieldnames: list[str] | None = None, delimiter: str = ",", quotechar: str = '"') -> None: ...
    def csv_update(self, path: str, data: list[dict[str, str]], identifier: str, delimiter: str = ",", quotechar: str = '"') -> None: ...
    def yaml_read(self, path: str, default: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def yaml_write(self, path: str, data: dict[str, Any]) -> None: ...
    def ini_read(self, path: str, default: dict[str, dict[str, str]] | None = None) -> dict[str, dict[str, str]]: ...
    def ini_write(self, path: str, data: dict[str, dict[str, str]], append: bool = False) -> None: ...
    def properties_read(self, path: str) -> dict[str, str]: ...
    def properties_write(self, path: str, data: dict[str, str], append: bool = False) -> None: ...
